### ISSUE TITLE
Some questions and suggestions

### ISSUE THREAD

**Issue by acch** [acch/ansible-scale-gui#1]
This is great work! :tada: I have a few comments, though:

- [x] Why install callhome RPMs (`scale_gui_callhome_rpms`) with this role? Is it a dependency? Is callhome integrated with the GUI? Otherwise I'd move callhome installation and configuration out into a separate, optional role. I never install callhome when installing GUI...

- [x] `configure.yml` is fairly long. Shall we put some logic into separate files and include them individually in `main.yml`? e.g. `callhome.yml`, `ldap.yml`, `email.yml`, etc. This could be a conditional include, so within the file we don't need to check `scale_gui_ldap_integration | bool` again and again upon each and every task.

- [x] I wonder if it wouldn't be more efficient to define optional configuration (e.g. LDAP config) like so:
  ```
  scale_gui_ldap_integration: false
  scale_gui_ldap:
    name: 'myad'
    host: 'myad.mydomain.local'
    bindDn: 'CN=servicebind,CN=Users,DC=mydomain,DC=local'
    ...
  ```
  Such vars could then be referenced like so: `scale_gui_ldap.name`...

- [x] `run_once: true` defaults to running on the first host in the play, so `delegate_to: "{{ ansible_play_hosts | first }}"` is not needed.

- [ ] Please remove any `debug` tasks and `TODO` comments prior to publication.

- [x] Please prefix all variables with `scale_gui_` to avoid collisions. I'd suggest to also prefix registered variables:
  ```
  # find . -type f -exec grep 'register:' {} \;
  register: conf_pmcollector_check
  register: conf_pmcollector
  register: conf_perfmon_check
  register: conf_enable_node_perfmon
  register: conf_initgui
  register: conf_gui_password_policy
  register: conf_gui_admin_check
  register: conf_createadmin
  register: conf_create_gui_user
  register: conf_callhome_check
  register: conf_callhome_autogroup_check
      register: conf_callhome_group
      register: conf_callhome_enable_proxy
      register: conf_callhome_enable
      register: conf_callhome_test
  register: conf_lsldap
  register: conf_lsusergrp
  register: conf_email_notifications_check
  register: conf_email_notifications
  register: conf_email_recipient_check
  register: conf_email_recipient
  register: conf_snmp_notifications_check
  register: conf_snmp_notifications
  register: conf_gui_vault_admin_check
  register: scale_cluster_clustername
  register: lshttpskeystore
  ```

- [ ] Searching a command's output for a specific string should only be used if there's REALLY no other way to determine if something was successful or not. Command output is likely going to change, and that will easily break the role:
  ```
  - " 'mmperfmon: There is no performance monitoring configuration data.' in conf_pmcollector_check.stderr"
  ```
  ```
  failed_when: "conf_enable_node_perfmon.rc != 0 and 'Propagating the cluster configuration data to all.' not in conf_enable_node_perfmon.stdout"
  ```
  Checking the return code or checking the existence of stdout / stderr is way better, e.g.:
  ```
    when:
    - not hostvars[item].scale_cluster_clusterId.stdout
    - hostvars[item].scale_cluster_clusterId.stderr
  ```
  ... but I know that it's not always possible...

**Comment by olemyk** [comment]
Hi Achim.
Thanks for the feedback, this is why we have review! 

Have done following: 

- Removed Callhome. (will create seperate roles)
- Created task for each configuration. like ldap, users, email, snmp,
- Created define optional configuration, so that all variables dont have long strings.
- Removed delegate_to, this is when we don't have inventory host vars.
- Prefix all variables with scale_gui_
- Tried to remove as much as possible of command's output for a specific string, only error codes. **open for suggestions here.**
- Updated readme with the parameters and information. should be just be spell checked. 

The Role seems to be stable now, but there is maybe som smartnes to the config.yaml and performance config that could be better,.

**Comment by acch** [comment]
Thanks much - looks great to me! Things can always be improved...

What do you think, is this a MVP (I'd say yes)? If so, do you want to set this repo to public?

**Comment by olemyk** [comment]
Updated som more on the code. (More Code Cleanup)
As you say, there is always more to improved, but this can be used by others now. 
So yes, make the repo public. =)  🎉

**Comment by acch** [comment]
Sorry for the delay. Repo is public now! :tada: 

Thanks much for your efforts!
